name: Docker image maker

on:
  push

jobs:
  build_and_publish:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      run: |
        docker login --username deep-jiwan --password ${{secrets.GH_ACCESS}} ghcr.io
        docker build . --tag ghcr.io/deep-jiwan/weatherappv3:ghlatest
        docker push ghcr.io/deep-jiwan/weatherappv3:ghlatest
        